### PR TITLE
Add GUADEC 2016 version with GNOME foot bullet points.

### PR DESCRIPTION
**Pull request by benzea**
Changes:
- Change aspect ratio to 16:10 (which should be what we have)
- Change year and dates
- use GNOME foot for bullet points
- change skyline
- Change city name

### CODE REVIEW

**Comment by sils** [comment]
Hey, this repo has moved to https://git.gnome.org/browse/presentation-templates/

**Comment by sils** [comment]
Alright, https://github.com/sils1297/guadec-presentation-templates/issues/12#issuecomment-224430472 is set up for issues and PRs.

**Comment by benzea** [comment]
Aha! And I tried to search git.gnome.org for "guadec" …

**Pull request closed without merging**
